# Generated by Django 3.2 on 2021-04-15 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='The users who can edit the project.',
                                         related_name='collaborates_in', to=settings.AUTH_USER_MODEL),
        ),
        # No projects should be in the db before this migration is run, so this should be fine
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=0, help_text='The user who owns the project, and has full access to it.',
                                    on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(
                choices=[('PUBLIC', '🌍 Public'), ('INTERNAL', '🏭 Internal'), ('PRIVATE', '🔒 Private')],
                default='INTERNAL', help_text='A setting specifying who can view the project.', max_length=16,
                verbose_name='Visibility'),
        ),
    ]
