# Generated by Django 3.2 on 2021-08-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchgroup',
            options={},
        ),
    ]
