# Generated by Django 3.2 on 2021-04-18 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20210415_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataflow',
            old_name='id',
            new_name='sdmx_id',
        ),
    ]
