# Generated by Django 3.2 on 2021-09-01 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_researchgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of what the group is about.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='researchgroup',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='The users who belong to this group.', null=True, related_name='is_a_member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
