# Generated by Django 3.2 on 2021-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_id_dataflow_sdmx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflow',
            name='surrogate_id',
            field=models.BigAutoField(help_text='Internal id used by Django to identify this DataFlow.', primary_key=True, serialize=False, verbose_name='Surrogate id'),
        ),
    ]
