# Generated by Django 3.2.7 on 2021-10-20 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20211016_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='The users who belong to this group.', related_name='is_a_member_of',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
