# Generated by Django 3.2 on 2021-08-06 19:18

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210806_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('slug', models.SlugField(help_text='Unique alphanumeric string which identifies the tag.', max_length=64, primary_key=True, serialize=False, verbose_name='Slug')),
                ('name', models.CharField(help_text='The name of the tag.', max_length=512, verbose_name='Name')),
                ('description', models.TextField(help_text='Additional information about the tag.', verbose_name='Description')),
                ('color', colorfield.fields.ColorField(default='#FF7F00', help_text='The color that the tag should have when displayed.', max_length=18, verbose_name='Color')),
                ('owner', models.ForeignKey(help_text='The user who created the tag, and therefore can delete it.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='researchproject',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags this project has been tagged with.', related_name='tagged', to='core.ResearchTag'),
        ),
    ]
