# Generated by Django 3.2 on 2021-08-08 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210806_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchtag",
            name="owner",
        ),
        migrations.AddField(
            model_name="researchtag",
            name="group",
            field=models.ForeignKey(
                to='core.researchgroup',
                help_text="The group this project belongs to.",
                on_delete=models.CASCADE,
            )
        )
    ]
