# Generated by Django 3.2 on 2021-09-01 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='container_id',
            field=models.CharField(blank=True, help_text='The id of the Docker container running this notebook. If null, the notebook is not running.',
                                   max_length=256, null=True, verbose_name='Container ID'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='The user who locked this notebook. If null, the notebook is unlocked.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='port',
            field=models.IntegerField(blank=True,
                                      help_text='The port number of the local machine at which the container is available. If null, the notebook is not running.',
                                      null=True, validators=[django.core.validators.MinValueValidator(49152), django.core.validators.MaxValueValidator(65535)],
                                      verbose_name='Local port number'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='volume_id',
            field=models.CharField(blank=True,
                                   help_text="The id of the Docker volume containing the data of this notebook. If null, the notebook doesn't currently have a volume, and will be created the next time the container is started.",
                                   max_length=256, null=True, verbose_name='Volume ID'),
        ),
    ]
