# Generated by Django 3.2 on 2021-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0007_alter_notebook_internet_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='container_image',
            field=models.CharField(choices=[('jupyter/base-notebook', 'Base'), ('jupyter/minimal-notebook', 'Python'), ('jupyter/scipy-notebook', 'Python (Scientific)'), ('jupyter/tensorflow-notebook', 'Python (Tensorflow)'), ('jupyter/r-notebook', 'Python + R'), ('jupyter/pyspark-notebook', 'Python (Scientific) + Apache Spark'), ('jupyter/all-spark-notebook', 'Python (Scientific) + Scala + R + Apache Spark'), ('steffo45/jupyterlab-docker-sophon', 'Python (Sophonic)')], default='steffo45/jupyterlab-docker-sophon', help_text='The Docker image to run for this notebook.', max_length=256, verbose_name='Docker image'),
        ),
    ]
