# Generated by Django 3.2.7 on 2021-10-18 18:02

from django.db import migrations, models

import sophon.notebooks.validators


class Migration(migrations.Migration):
    dependencies = [
        ('notebooks', '0008_alter_notebook_container_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(
                help_text='Unique alphanumeric string which identifies the project. Changing this once the container has been created <strong>will break Docker</strong>!',
                max_length=64, primary_key=True, serialize=False,
                validators=[sophon.notebooks.validators.DisallowedValuesValidator(['api', 'proxy', 'backend', 'frontend', 'src'])], verbose_name='Slug'),
        ),
    ]
