# Generated by Django 3.2.7 on 2021-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notebooks', '0011_auto_20211019_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='internal_url',
            field=models.CharField(blank=True,
                                   help_text='The URL reachable from the proxy where the container is available. Can be null if the notebook is not running.',
                                   max_length=512, null=True, verbose_name='Internal URL'),
        ),
    ]
