# Generated by Django 3.2.7 on 2021-10-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notebooks', '0012_alter_notebook_internal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='container_image',
            field=models.CharField(choices=[('ghcr.io/steffo99/sophon-jupyter', 'Python (Sophonic)')], default='steffo45/jupyterlab-docker-sophon',
                                   help_text='The Docker image to run for this notebook.', max_length=256, verbose_name='Docker image'),
        ),
    ]
