# Generated by Django 3.2.8 on 2021-11-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notebooks', '0014_alter_notebook_container_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='container_image',
            field=models.CharField(choices=[('ghcr.io/steffo99/sophon-jupyter', 'Jupyter (Sophon)')], default='ghcr.io/steffo99/sophon-jupyter',
                                   help_text='The Docker image to run for this notebook.', max_length=256, verbose_name='Docker image'),
        ),
    ]
