# Generated by Django 3.1.7 on 2021-04-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210405_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='The sources used by this project.', related_name='used_in', to='core.DataSource'),
        ),
    ]
