# Generated by Django 3.2 on 2021-04-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflow',
            name='last_update',
            field=models.DateTimeField(auto_now=True, help_text='The datetime at which the properties of this DataFlow were last updated.', verbose_name='Last updated'),
        ),
    ]
