# Generated by Django 3.2 on 2021-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the project, to be displayed in the overview.', null=True, verbose_name='Description'),
        ),
    ]
