name: Build report document
on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-sphinx-report.yml"
      - "report/**"
      - "backend/**"
jobs:
  html:
    name: "Build HTML document"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: "Install backend dependencies"
        working-directory: backend/
        run: "poetry install --no-interaction"
      - name: "Find Poetry Python environment"
        run: echo "pythonLocation=$(poetry env list --full-path | cut -f1 -d' ')/bin" >> $GITHUB_ENV
      - name: "Build HTML document with Sphinx"
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "report/"
          build-command: "make html"
      - name: "Create a gzip of the build"
        run: "tar -xvzf report/_build/report.html.tar.gz report/_build/html"
      - name: "Upload build artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "report.html.tar.gz"
          path: "report/_build/report.html.tar.gz"
  latexpdf:
    name: "Build PDF document"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: "Install backend dependencies"
        working-directory: backend/
        run: poetry install --no-interaction
      - name: "Find Poetry Python environment"
        run: echo "pythonLocation=$(poetry env list --full-path | cut -f1 -d' ')/bin" >> $GITHUB_ENV
      - name: "Install Latex dependencies"
        run: apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
      - name: "Build Latex document with Sphinx"
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "report/"
          build-command: "make latexpdf"
      - name: "Upload build artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "report.pdf"
          path: "report/_build/latex/sophon.pdf"
